name = "PowerNumbers"
uuid = "7635a310-babe-11e9-2fde-a3dff3ddcf26"
authors = ["idlemat <52246739+idlemat@users.noreply.github.com>"]
version = "0.0.1"

[deps]
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
Infinities = "e1ba4f0e-776d-440f-acd9-e1d2e9742647"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
RecurrenceRelationshipArrays = "b889d2dc-af3c-4820-88a8-238fa91d3518"

[extensions]
PowerNumbersRecurrenceRelationshipArraysExt = "RecurrenceRelationshipArrays"

[compat]
DualNumbers = "0.6"
Infinities = "0.1"
LinearAlgebra = "1.10"
RecurrenceRelationshipArrays = "0.1.5"
julia = "1.10"

[extras]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
RecurrenceRelationshipArrays = "b889d2dc-af3c-4820-88a8-238fa91d3518"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HypergeometricFunctions", "IntervalArithmetic", "RecurrenceRelationshipArrays"]
